#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export TERM="xterm-256color"
export LC_CTYPE="en_US.UTF-8"
export LANG="en_US.UTF-8"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

ostype() { echo $OSTYPE | tr '[A-Z]' '[a-z]'; }

SHELL_PLATFORM='unknown'
case "$(ostype)" in
  *'linux'*  ) SHELL_PLATFORM='linux' ;;
  *'darwin'* ) SHELL_PLATFORM='osx' ;;
  *'bsd'*    ) SHELL_PLATFORM='bsd' ;;
esac
export SHELL_PLATFORM

java_homes=(
  /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home
  /usr/java/jdk
)
for h in $java_homes
do
  if [[ -e "$h/bin/java" ]]; then
    export JAVA_HOME="$h"
    break
  fi
done
export CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar

export M2_HOME=/opt/develop/maven/3.3.9
export MAVEN_OPTS="-Xms256m -Xmx1024m -Dfile.encoding=UTF-8"

export SCALA_HOME=/opt/develop/scala/current

export SBT_HOME=/opt/develop/sbt

export ANDROID_HOME=/usr/local/opt/android-sdk
export ANDROID_NDK_HOME=/usr/local/opt/android-ndk
export NDK_ROOT="$ANDROID_NDK_HOME"

export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$CUDA_HOME/lib"

export GOPATH=~/go

export GTAGSLIBPATH=$HOME/.gtags/

export NODE_PATH=~/.nvm/versions/node/v5.0.0/lib/node_modules

export MAGICK_HOME="/opt/ImageMagick-7.0.1"

export VIRTUALENVWRAPPER_PYTHON=`which python`
export VIRTUALENVWRAPPER_VIRTUALENV=`which virtualenv`
export PYTHONPATH="$HOME/local/lib/python2.7/site-packages"

export LD_LIBRARY_PATH=~/usr/lib:/usr/local/cuda/lib64/:/usr/lib64/atlas/:/usr/local/cuda/lib/
export C_INCLUDE_PATH=~/usr/include:/usr/local/cuda/include/
export CPLUS_INCLUDE_PATH=~/usr/include:/usr/local/cuda/include/
export LIBRARY_PATH=~/usr/lib:/usr/lib64/atlas/:/usr/local/cuda/lib64/

export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig/

export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:/usr/local/opt/gnu-sed/libexec/gnuman:$MANPATH"

if [[ "$SHELL_PLATFORM" == 'osx' ]]; then
  export LIBRARY_PATH=/usr/local/ssl/macos-x86_64/lib/:$LIBRARY_PATH
  export LD_LIBRARY_PATH=/usr/local/ssl/macos-x86_64/lib/:$LD_LIBRARY_PATH
  export C_INCLUDE_PATH=/usr/local/ssl/macos-x86_64/include/:$C_INCLUDE_PATH
  export CPLUS_INCLUDE_PATH=/usr/local/ssl/macos-x86_64/include/:$C_INCLUDE_PATH

  export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles
fi

export PATH="$CUDA_HOME/bin:/usr/local/ssl/macos-x86_64/bin/:$PATH"
export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$SCALA_HOME/bin:$SBT_HOME/bin:~/.cabal/bin:$GOPATH/bin:$HOME/.rvm/bin:$PATH
export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/25.0.2:$ANDROID_NDK_HOME/bin:$PATH
export PATH=$HOME/bin:$HOME/local/bin:$HOME/.local/bin:$HOME/.linuxbrew/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/bin:/opt/develop/jetbrains/idea-IU/bin:/opt/develop/jetbrains/WebStorm/bin:$PATH

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
